DROP TABLE STUDIO CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE SERVICE CASCADE CONSTRAINTS;
DROP TABLE APPOINTMENT CASCADE CONSTRAINTS;
DROP SEQUENCE seqCID;
DROP SEQUENCE seqEID;
DROP SEQUENCE seqSID;
DROP SEQUENCE seqAID;

CREATE TABLE STUDIO (
    StudioId  INT NOT NULL,
    Location   VARCHAR(255),
    CONSTRAINT  SERV_PK PRIMARY KEY(ServiceId)
);
CREATE SEQUENCE seqSTID INCREMENT BY 1 START WITH 1;

CREATE TABLE CUSTOMER (
    CustomerId  INT NOT NULL,
    LastName    CHAR(30),
    FirstName   CHAR(30),
    CONSTRAINT  CUST_PK PRIMARY KEY(CustomerId)
);

CREATE SEQUENCE seqCID INCREMENT BY 1 START WITH 1;

CREATE TABLE EMPLOYEE (
    EmployeeId  INT NOT NULL,
    LastName    CHAR(30),
    FirstName   CHAR(30),
    Role        CHAR(10),
    StudioId    INT,
    CONSTRAINT  EMP_PK PRIMARY KEY(EmployeeId),
    CONSTRAINT  EMP_STUDIO_FK FOREIGN KEY (StudioId)
                    REFERENCES STUDIO(StudioId)
);

CREATE SEQUENCE seqEID INCREMENT BY 1 START WITH 1;

CREATE TABLE SERVICE (
    ServiceId  INT NOT NULL,
    Type    CHAR(30),
    RequiredStaff CHAR(30),
    PricePerHour    NUMBER(5,2),
    CONSTRAINT  SERV_PK PRIMARY KEY(ServiceId)
);
CREATE SEQUENCE seqSID INCREMENT BY 1 START WITH 1;

CREATE TABLE APPOINTMENT (
    ApptId  INT NOT NULL,
    StartTime   TIMESTAMP,
    EndTime     TIMESTAMP,
    CustomerId  INT,
    ServiceId   INT,
    EmployeeId  INT,
    StudioId    INT,
    CONSTRAINT  APPT_PK PRIMARY KEY(ApptId),
    CONSTRAINT			APPT_CUST_FK FOREIGN KEY (CustomerId)
							REFERENCES CUSTOMER(CustomerId),
    CONSTRAINT			APPT_SERV_FK FOREIGN KEY (ServiceId)
							REFERENCES SERVICE(ServiceId),
	CONSTRAINT			APPT_EMP_FK FOREIGN KEY (EmployeeId)
							REFERENCES EMPLOYEE(EmployeeId),
    CONSTRAINT			APPT_STUDIO_FK FOREIGN KEY (StudioId)
                            REFERENCES STUDIO(StudioId)
);

CREATE SEQUENCE seqAID INCREMENT BY 1 START WITH 1;
